### ISSUE TITLE
[bug] Fails To Start In SMP

### ISSUE THREAD

**Issue by nephatrine** [ix0rai/bodaciousberries#30]
**describe the bug**
Mod seems to work perfectly in single-player, but when on a dedicated server the server fails to start. Looks like maybe it is trying to call client apis from the server?

**log**
```
[14:43:16] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bodaciousberries'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.2.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.2.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [fabric-1.18.1-0.13.2.jar:0.10.2]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/blockrenderlayer/v1/BlockRenderLayerMap
	at io.ix0rai.bodaciousberries.block.BasicBerryBush.<init>(BasicBerryBush.java:83) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.block.ChorusBerryBush.<init>(ChorusBerryBush.java:12) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.registry.Bushes.<clinit>(Bushes.java:28) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.Bodaciousberries.onInitialize(Bodaciousberries.java:20) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
	... 16 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at io.ix0rai.bodaciousberries.block.BasicBerryBush.<init>(BasicBerryBush.java:83) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.block.ChorusBerryBush.<init>(ChorusBerryBush.java:12) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.registry.Bushes.<clinit>(Bushes.java:28) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at io.ix0rai.bodaciousberries.Bodaciousberries.onInitialize(Bodaciousberries.java:20) ~[bodaciousberries-1.1.1+mc1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.2.jar:?]
	... 16 more
```

**version**
`bodaciousberries-1.1.1+mc1.18.1.jar`

**Comment by eristhea** [comment]
hello! thank you for reporting
this should be fixed in [this version](https://modrinth.com/mod/berries/version/ucivDAmI)
please reopen if you see it again!
