### ISSUE TITLE
[bug] crash report  - game wont launch

### ISSUE THREAD

**Issue by garogan** [ix0rai/bodaciousberries#47]
version  Bodacious Berries 1.4.6+mc1.18.2

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/15/22, 7:19 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'bodaciousberries'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:69)
		at com.hugman.culinaire.init.client.CulinaireScreens.init(CulinaireScreens.java:12)
		at com.hugman.culinaire.CulinaireClient.onInitializeClient(CulinaireClient.java:14)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:69)
		at com.glisco.disenchanter.client.DisenchanterClient.onInitializeClient(DisenchanterClient.java:29)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:69)
		at draylar.inmis.InmisClient.onInitializeClient(InmisClient.java:19)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:69)
		at net.id.aether.screen.AetherScreens.register(AetherScreens.java:36)
		at net.id.aether.screen.AetherScreens.initClient(AetherScreens.java:23)
		at net.id.aether.Aether.onInitializeClient(Aether.java:122)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_3929
		at net.fabricmc.fabric.api.client.screenhandler.v1.ScreenRegistry.register(ScreenRegistry.java:69)
		at net.blay09.mods.balm.fabric.client.screen.FabricBalmScreens.registerScreen(FabricBalmScreens.java:18)
		at net.blay09.mods.waystones.client.ModScreens.initialize(ModScreens.java:12)
		at net.blay09.mods.waystones.client.WaystonesClient.initialize(WaystonesClient.java:13)
		at net.blay09.mods.balm.fabric.client.FabricBalmClientRuntime.initialize(FabricBalmClientRuntime.java:57)
		at net.blay09.mods.balm.api.client.BalmClient.initialize(BalmClient.java:16)
		at net.blay09.mods.waystones.client.FabricWaystonesClient.onInitializeClient(FabricWaystonesClient.java:11)
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
		... 11 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.minecraft.class_3929.<clinit>(class_3929.java:90)
	at io.ix0rai.bodaciousberries.client.BodaciousberriesClient.onInitializeClient(BodaciousberriesClient.java:19)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_471 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyLimit(I)I in limitless.mixins.json:anvil.AnvilScreenMixin from mod limitless failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap limitless-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.2203.5 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.1151 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		OleAut32.dll:OLEAUT32.DLL:10.0.19041.985 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.1620 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.19041.1415 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.19041.1320 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.19041.1503 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll
		java.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		javaw.exe:OpenJDK Platform binary:17.0.1.0:Microsoft
		jimage.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		jna9672358325578513176.dll:JNA native library:6.1.2:Java(TM) Native Access (JNA)
		jvm.dll:OpenJDK 64-Bit server VM:17.0.1.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		mdnsNSP.dll:Bonjour Namespace Provider:3,0,0,10:Apple Inc.
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ntdll.dll:NT Layer DLL:10.0.19041.1682 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.19041.844 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		svml.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.19041.789 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30133.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
		win32u.dll:Win32u:10.0.19041.1706 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.1.0:Microsoft
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1418511016 bytes (1352 MiB) / 4160749568 bytes (3968 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f14
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1169
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 40529.69
	Virtual memory used (MB): 23023.69
	Swap memory total (MB): 8000.00
	Swap memory used (MB): 542.38
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.0
		advanced-xray-fabric: Advanced XRay (Fabric) 1.18.2-1.0.0-build.11
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		anvil_fix: AnvilFix 1.3.0
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.1.44
		autoconfig1u: Auto Config v1 Updated 3.4.0
		balm-fabric: Balm 3.0.0+0
		blue_endless_jankson: jankson 1.2.1
		bodaciousberries: Bodacious Berries 1.4.6+mc1.18.2
		byg: Oh The Biomes You'll Go 1.4-RC-8
		caffeineconfig: CaffeineConfig 1.1.0
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		carrier: Carrier 1.10.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		cloth-config-lite: cloth-config-lite 2.0.6
		clumps: Clumps 8.0.0+8
		cmods: Combined Modifiers 1.2.0
		coat: Coat 1.0.0-beta.17+mc1.18.2
		colytra: Colytra 2.1.1-1.18.1
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		complete_bone_meal: Complete Bone Meal 1.3.1
		config2brigadier: Config to Brigadier 1.0.2
		craftable_enchanted_golden_apple: Craftable Enchanted Golden Apple 1.0.2
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		cse: Craftable Spawn Eggs 1.0.0
		culinaire: Culinaire 2.4.0
		cullleaves: Cull Leaves 2.3.2
		customportalapi: Custom Portal Api 0.0.1-beta50-1.18
		dawn: Dawn API 3.3.0
		denseores: Dense Ores: Refabricated 1.2.2+1.18.2
		disenchanter: Disenchanter 0.1.6+1.18
		durabilityviewer: Giselbaers Durability Viewer 1.18.2-fabric0.47.10-1.10.3
		epicreloadmod: Epic Reload Mod 1.0.2
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.2+kotlin.1.6.20
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Quilted Fabric Rendering (v1) 2.0.0+1.18.2-SNAPSHOT
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		fabrilousupdater: FabrilousUpdater 2.6+1.18.2
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.4+1.18.2
		gud_recipe_confidence: Recipe Confidence 1.0.2
		healthcare: Health Care 1.0.11
		horsebuff: HorseBuff 1.2.3
		incubus_core: Incubus Core 1.6.6+1.18.2
		inmis: Inmis 2.6.0-1.18.2
		inspecio: Inspecio 1.3.0+1.18
		iris: Iris 1.2.2-build.32
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		journeymap-api-fabric: JourneyMap API 1.18.2-1.8-fabric-SNAPSHOT
		journeymap-fabric: Journeymap 5.8.3
		libgui: LibGui 5.3.1+1.18
		libninepatch: LibNinePatch 1.1.0
		limitless: limitless 1.6.7
		lithium: Lithium 0.7.9
		lod: Distant Horizons 1.6.3a
		mendinglevels: Mending Levels 1.0.1
		midnightlib: MidnightLib 0.4.0
		minecraft: Minecraft 1.18.2
		modmanager: Mod Manager 1.2.3+1.18
		modmenu: Mod Menu 3.2.1
		moretags: More Tags 3.0.3
		mostructures: Mo' Structures 1.4.2+1.18.2
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nbtcrafting: NBT Crafting 2.1.3+mc1.18.2
		net_auoeke_reflect: reflect 4.6.0
		net_gudenau_lib_unsafe: unsafe 1.7.1
		net_hypixel_hypixel-api-core: hypixel-api-core 4.1
		net_hypixel_hypixel-api-transport-apache: hypixel-api-transport-apache 4.1
		omega-config: OmegaConfig 1.2.3-1.18.1
		omega-config-gui: Omega Config GUI 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		osmium: Osmium 1.3.1-1.18.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		patchouli: Patchouli 1.18.2-67-FABRIC
		phosphor: Phosphor 0.8.1
		purpeille: Purpeille 2.1.1
		quilt_base: Quilt Base API 1.0.0+1.18.2-SNAPSHOT
		quilt_client_command: Quilt Client Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_command: Quilt Command API 1.0.0+1.18.2-SNAPSHOT
		quilt_lifecycle_events: Quilt Lifecycle Events 1.0.0+1.18.2-SNAPSHOT
		quilt_resource_loader: Quilt Resource Loader 1.0.0+1.18.2-SNAPSHOT
		quilt_tags: Quilt Tags API 1.0.0+1.18.2-SNAPSHOT
		quilt_tooltip: Quilt Tooltip API 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-api-base: Quilted Fabric API Base 1.0.0+1.18.2-SNAPSHOT
		quilted-fabric-command-api-v1: Quilted Fabric Command API (v1) 2.0.0+1.18.2-SNAPSHOT
		quilted-fabric-lifecycle-events-v1: Quilted Fabric Lifecycle Events (v1) 2.0.1+1.18.2-SNAPSHOT
		quilted-fabric-resource-loader-v0: Quilted Fabric Resource Loader (v0) 1.0.0+1.18.2-SNAPSHOT
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		rocks: This Rocks! 1.6.0
		roughlyenoughitems: Roughly Enough Items 8.0.442
		rpgstats: RPGStats 4.3.10+1.18.2
		satin: Satin 1.7.2
		server_translations_api: Server Translations API 1.4.10+1.18.2
		silkspawners: SilkSpawners 1.1.1
		simple_backpack: SimpleBackpack 1.2.35
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		spawnermod: Enhanced Mob Spawners 1.1.2
		spiceoffabric: Spice of Fabric 1.5.2+1.18.2
		stacc: Stacc 1.3.0
		stacker: Stacker 2.1.3
		stepup: StepUp 1.18.2-fabric0.47.10-1.1
		subterrestrial: Subterrestrial 1.0.2
		terrablender: TerraBlender 1.1.0.99
		the_aether: Paradise Lost 1.6.8+1.18.2
		timber: Timber 1.2.0+1.18.2
		trinkets: Trinkets 3.3.0
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18.2
		tweed4_base: tweed4_base 1.5.0+mc1.18.2
		tweed4_data: tweed4_data 1.2.1+mc1.18.2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18.2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		voidcrafting: Void Crafting 1.6.2
		walllanterns: Lanterns Belong on Walls 1.1.0
		waystones: Waystones 10.0.0
		yigd: You're in Grave Danger 1.3.4
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by eristhea** [comment]
minecraft says it best: // This doesn't make any sense!

Despite being called the culprit, I'm not sure bodacious berries is actually causing this error. Could you try without the mod `limitless`?

it seems like this is the root cause:
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyLimit(I)I in limitless.mixins.json:anvil.AnvilScreenMixin from mod limitless failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap limitless-refmap.json
```

**Comment by garogan** [comment]
I played around with removing mods and it looks like it was actually incompat between anvilFix and limitless, sorry about that! Your mod is all good :)

**Comment by Thonkman** [comment]
thanks for playing the mod!
